<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ana Carolina Balbino">
<meta name="keywords" content="Redes Sociais, Análise de Grafos, RAPIDS cuGraph, Computação Paralela, GPU">

<title>1&nbsp; Análise Estrutural e Algorítmica da Rede Social LiveJournal – ANALISANDO SNAP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./parte1_all.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2b384705af00959c2399f46f5d610324.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2f7803d31673bca6e969e47723c7a1ec.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./paper.html">Relatório</a></li><li class="breadcrumb-item"><a href="./paper.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Análise Estrutural e Algorítmica da Rede Social LiveJournal</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./grafos.gif" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./grafos.gif" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ANALISANDO SNAP</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/carolbalbs/tp-final" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introdução</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Relatório</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./paper.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Análise Estrutural e Algorítmica da Rede Social LiveJournal</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Scripts</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parte1_all.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análise Estrutura - Comunidades</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parte1_ungraph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Análise Estrutura - Grafo Completo</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#cálculo-de-determinação-do-grafo-a-ser-utilizado" id="toc-cálculo-de-determinação-do-grafo-a-ser-utilizado" class="nav-link active" data-scroll-target="#cálculo-de-determinação-do-grafo-a-ser-utilizado"><span class="header-section-number">2</span> Cálculo de Determinação do Grafo a ser Utilizado</a></li>
  <li><a href="#descrição-do-grafo-original" id="toc-descrição-do-grafo-original" class="nav-link" data-scroll-target="#descrição-do-grafo-original"><span class="header-section-number">3</span> Descrição do Grafo Original</a></li>
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">4</span> Metodologia</a>
  <ul class="collapse">
  <li><a href="#dataset-e-formato-de-entrada" id="toc-dataset-e-formato-de-entrada" class="nav-link" data-scroll-target="#dataset-e-formato-de-entrada"><span class="header-section-number">4.1</span> Dataset e Formato de Entrada</a></li>
  <li><a href="#ambiente-computacional" id="toc-ambiente-computacional" class="nav-link" data-scroll-target="#ambiente-computacional"><span class="header-section-number">4.2</span> Ambiente Computacional</a></li>
  <li><a href="#procedimento-de-análise-estrutural" id="toc-procedimento-de-análise-estrutural" class="nav-link" data-scroll-target="#procedimento-de-análise-estrutural"><span class="header-section-number">4.3</span> Procedimento de Análise Estrutural</a></li>
  <li><a href="#avaliação-de-algoritmos" id="toc-avaliação-de-algoritmos" class="nav-link" data-scroll-target="#avaliação-de-algoritmos"><span class="header-section-number">4.4</span> Avaliação de Algoritmos</a></li>
  </ul></li>
  <li><a href="#resultados-obtidos" id="toc-resultados-obtidos" class="nav-link" data-scroll-target="#resultados-obtidos"><span class="header-section-number">5</span> Resultados Obtidos</a>
  <ul class="collapse">
  <li><a href="#tratamento-dos-dados" id="toc-tratamento-dos-dados" class="nav-link" data-scroll-target="#tratamento-dos-dados"><span class="header-section-number">5.1</span> Tratamento dos Dados</a></li>
  <li><a href="#análise-estrutural-do-grafo-completo" id="toc-análise-estrutural-do-grafo-completo" class="nav-link" data-scroll-target="#análise-estrutural-do-grafo-completo"><span class="header-section-number">5.2</span> Análise Estrutural do Grafo Completo</a></li>
  <li><a href="#desempenho-dos-algoritmos" id="toc-desempenho-dos-algoritmos" class="nav-link" data-scroll-target="#desempenho-dos-algoritmos"><span class="header-section-number">5.3</span> Desempenho dos Algoritmos</a></li>
  <li><a href="#propriedade-small-world" id="toc-propriedade-small-world" class="nav-link" data-scroll-target="#propriedade-small-world"><span class="header-section-number">5.4</span> Propriedade Small-World</a></li>
  <li><a href="#análise-de-lei-de-potência-power-law" id="toc-análise-de-lei-de-potência-power-law" class="nav-link" data-scroll-target="#análise-de-lei-de-potência-power-law"><span class="header-section-number">5.5</span> Análise de Lei de Potência (Power Law)</a></li>
  <li><a href="#robustez-da-rede" id="toc-robustez-da-rede" class="nav-link" data-scroll-target="#robustez-da-rede"><span class="header-section-number">5.6</span> Robustez da Rede</a></li>
  </ul></li>
  <li><a href="#discussão-crítica" id="toc-discussão-crítica" class="nav-link" data-scroll-target="#discussão-crítica"><span class="header-section-number">6</span> Discussão Crítica</a>
  <ul class="collapse">
  <li><a href="#decisões-de-projeto-e-viabilidade" id="toc-decisões-de-projeto-e-viabilidade" class="nav-link" data-scroll-target="#decisões-de-projeto-e-viabilidade"><span class="header-section-number">6.1</span> Decisões de Projeto e Viabilidade</a></li>
  <li><a href="#limitações-metodológicas-e-estruturais" id="toc-limitações-metodológicas-e-estruturais" class="nav-link" data-scroll-target="#limitações-metodológicas-e-estruturais"><span class="header-section-number">6.2</span> Limitações Metodológicas e Estruturais</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">7</span> Conclusão</a>
  <ul class="collapse">
  <li><a href="#agradecimentos" id="toc-agradecimentos" class="nav-link" data-scroll-target="#agradecimentos">Agradecimentos</a></li>
  </ul></li>
  <li><a href="#apêndice" id="toc-apêndice" class="nav-link" data-scroll-target="#apêndice">Apêndice</a>
  <ul class="collapse">
  <li><a href="#repositório-e-instruções-de-execução" id="toc-repositório-e-instruções-de-execução" class="nav-link" data-scroll-target="#repositório-e-instruções-de-execução"><span class="header-section-number">7.1</span> Repositório e Instruções de Execução</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/carolbalbs/tp-final/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./paper.html">Relatório</a></li><li class="breadcrumb-item"><a href="./paper.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Análise Estrutural e Algorítmica da Rede Social LiveJournal</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Análise Estrutural e Algorítmica da Rede Social LiveJournal</span></h1>
<p class="subtitle lead">Relatório de Experimento - Teoria dos Grafos (MATA53)</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Ana Carolina Balbino <a href="mailto:ana.balbino@ufba.br" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidade Federal da Bahia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Redes Sociais, Análise de Grafos, RAPIDS cuGraph, Computação Paralela, GPU</p>
  </div>
</div>

</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<blockquote class="blockquote">
<p>Você pode fazer o download da versão formatada em PDF deste artigo aqui: <a href="224115861.pdf">relatorio.pdf</a></p>
</blockquote>
</div>
</div>
</div>
<section id="cálculo-de-determinação-do-grafo-a-ser-utilizado" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Cálculo de Determinação do Grafo a ser Utilizado</h1>
<p>De acordo com a regra de mapeamento determinada nas orientações do trabalho, dado o número de matrícula <span class="math inline">\(M\)</span>, o ID do grafo a ser selecionado é dado por: <span class="math display">\[
f(M) = ((\text{soma dos dígitos de } M) \times (\text{últimos 2 dígitos de } M + 1)) \bmod 129
\]</span></p>
<p>Para a matrícula <strong>224115861</strong>: - Soma dos dígitos = <span class="math inline">\(2 + 2 + 4 + 1 + 1 + 5 + 8 + 6 + 1 = 30\)</span> - Últimos dois dígitos = <span class="math inline">\(61\)</span></p>
<p>O cálculo resultante é: <span class="math display">\[
f(M) = (30 \times (61 + 1)) \bmod 129 = (30 \times 62) \bmod 129 = 1860 \bmod 129 = 25
\]</span></p>
<p>Conforme o ID obtido na planilha de referência, o conjunto de dados correspondente é o <strong>“LiveJournal social network and ground-truth communities”</strong>, pertencente à categoria de redes sociais e comunidades ground-truth, caracterizado por ser um grafo não direcionado com comunidades reais.</p>
<div id="fig-selecao-dataset" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-selecao-dataset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/images/fig1_selecao_dataset.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-selecao-dataset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Seleção do dataset conforme a regra de mapeamento no site do SNAP
</figcaption>
</figure>
</div>
<p>O código-fonte completo deste projeto, incluindo scripts de processamento e execução dos experimentos, está disponível no GitHub: - <strong>Repositório:</strong> <a href="https://github.com/Carolbalbs/tp-final" class="uri">https://github.com/Carolbalbs/tp-final</a></p>
</section>
<section id="descrição-do-grafo-original" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Descrição do Grafo Original</h1>
<p>O conjunto de dados utilizado neste trabalho foi o <em>LiveJournal social network and ground-truth communities</em>, disponibilizado pelo <em>Stanford Network Analysis Project</em> (SNAP) <span class="citation" data-cites="yang2012">(<a href="#ref-yang2012" role="doc-biblioref">Yang and Leskovec 2012</a>)</span>. Trata-se de uma das maiores redes sociais não direcionadas disponíveis publicamente, contendo 3.997.962 nós e 34.681.189 arestas, onde os nós representam usuários e as arestas indicam conexões de amizade.</p>
<p>O LiveJournal é uma comunidade virtual na qual os usuários mantêm blogs, diários e interagem entre si. O dataset modela essa rede e fornece informações sobre comunidades reais estruturadas de forma implícita pelas interações dos usuários. A análise exata de suas propriedades estruturais (como diâmetro) ou o cálculo de caminhos mínimos de todos para todos (complexidade <span class="math inline">\(O(V^3)\)</span> ou <span class="math inline">\(O(V^2 E)\)</span>) é inviável em sistemas CPU tradicionais devido à escala da rede.</p>
<p>Por esse motivo, neste trabalho, adotou-se o uso de processamento paralelo em GPU por meio da biblioteca cuGraph (suíte NVIDIA RAPIDS), o que permitiu obter métricas globais e executar buscas no grafo completo em frações de segundo.</p>
<p>As informações básicas fornecidas no repositório do SNAP sobre o dataset são descritas nas tabelas a seguir.</p>
<div id="tbl-arquivos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-arquivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Informações dos arquivos do dataset
</figcaption>
<div aria-describedby="tbl-arquivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Arquivo</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>com-lj.ungraph.txt</code></td>
<td style="text-align: left;">Grafo de amizade completo</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>com-lj.top5000.cmty.txt</code></td>
<td style="text-align: left;">Top 5000 comunidades</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>com-lj.all.cmty.txt</code></td>
<td style="text-align: left;">Todas as comunidades</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-oficial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-oficial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.2: Informações estruturais disponíveis no site oficial
</figcaption>
<div aria-describedby="tbl-oficial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Métrica</th>
<th style="text-align: left;">Valor Oficial (SNAP)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coeficiente médio de clusterização</td>
<td style="text-align: left;"><span class="math inline">\(\approx 0,284\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Diâmetro</td>
<td style="text-align: left;"><span class="math inline">\(17\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diâmetro efetivo (90%)</td>
<td style="text-align: left;"><span class="math inline">\(\approx 6,5\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Triângulos</td>
<td style="text-align: left;"><span class="math inline">\(\approx 177.820.130\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A análise inicial dessas métricas revela uma rede densamente agrupada localmente, com forte presença de comunidades e caminhos médios curtos (propriedade small-world), características típicas de grandes redes sociais online.</p>
</section>
<section id="metodologia" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Metodologia</h1>
<section id="dataset-e-formato-de-entrada" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="dataset-e-formato-de-entrada"><span class="header-section-number">4.1</span> Dataset e Formato de Entrada</h2>
<p>O arquivo do grafo (<code>com-lj.ungraph.txt</code>) foi lido no formato de lista de adjacências contendo dois inteiros por linha separados por tabulação.</p>
</section>
<section id="ambiente-computacional" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="ambiente-computacional"><span class="header-section-number">4.2</span> Ambiente Computacional</h2>
<p>Os experimentos foram conduzidos em um servidor pertencente à infraestrutura do projeto <strong>BAMBU Lab</strong> (Rede Metropolitana para Experimentação e Inovação da Internet do Futuro), sediado na Universidade Federal da Bahia (UFBA).</p>
<p>O hardware utilizado consistiu em: - <strong>Placa de Vídeo (GPU):</strong> 2x NVIDIA RTX A4000 (16 GB de VRAM cada), utilizando exclusivamente a GPU de índice 1 (via variável de ambiente <code>CUDA_VISIBLE_DEVICES=1</code>). - <strong>Sistema Operacional:</strong> Linux (Ubuntu 22.04) - <strong>Tecnologias Core:</strong> CUDA 12.6, Drivers NVIDIA 560.35.03, Python 3.10 em container virtual gerenciado via Podman.</p>
<p>As principais bibliotecas de software empregadas foram: - <code>cuDF</code> e <code>cuGraph</code> (versão 24.xx): para manipulação paralela de dados e execução de algoritmos acelerados em GPU. - <code>NetworkX</code> (versão 3.4): utilizada como fallback na CPU para algoritmos sem suporte de hardware. - <code>NumPy</code>, <code>SciPy</code> e <code>Matplotlib</code>: para processamento estatístico, cálculos de intervalo de confiança e plotagem.</p>
<p>Para evitar vazamentos de memória na GPU e na CPU entre execuções repetidas, chamadas explícitas de coleta de lixo (<code>gc.collect()</code>) foram inseridas nos scripts após cada medição.</p>
</section>
<section id="procedimento-de-análise-estrutural" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="procedimento-de-análise-estrutural"><span class="header-section-number">4.3</span> Procedimento de Análise Estrutural</h2>
<p>As propriedades estruturais básicas do grafo completo foram calculadas diretamente sobre a GPU. Para as métricas que dependem de caminhos mínimos globais (como diâmetro, raio e distância média), as quais possuem custo computacional proibitivo de <span class="math inline">\(O(V \cdot E)\)</span> na GPU, aplicou-se uma metodologia de <strong>amostragem aleatória com <span class="math inline">\(k = 500\)</span> nós de origem</strong>.</p>
<p>Para cada nó da amostra, executou-se uma busca em largura (BFS) e armazenou-se a excentricidade e a distribuição de caminhos mais curtos. Os valores estatísticos reportados foram calculados com base nessa amostra, acompanhados de intervalos de confiança de 95%.</p>
</section>
<section id="avaliação-de-algoritmos" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="avaliação-de-algoritmos"><span class="header-section-number">4.4</span> Avaliação de Algoritmos</h2>
<p>Implementou-se a medição de tempo dos seguintes algoritmos: BFS, DFS, verificação de Eulerianidade, Dijkstra, Bellman-Ford, Floyd-Warshall, Tarjan, Prim e Kruskal. - Algoritmos com complexidade linear ou quase linear no número de arestas (<span class="math inline">\(O(V+E)\)</span> ou <span class="math inline">\(O(E \log V)\)</span>) foram executados sobre o <strong>grafo completo</strong> (e.g., BFS, DFS, Eulerianidade, Prim, Kruskal). - Devido às elevadas complexidades de Bellman-Ford (<span class="math inline">\(O(V \cdot E)\)</span>) e Floyd-Warshall (<span class="math inline">\(O(V^3)\)</span>), suas execuções foram realizadas em um <strong>subgrafo induzido de 1.000 nós</strong> selecionados aleatoriamente, preservando a conectividade. - Algoritmos que exigem pesos (como Dijkstra) ou direcionalidade (como Tarjan) não foram medidos no benchmark de desempenho por limitações estruturais do grafo LiveJournal (não direcionado e não ponderado). - Para cada algoritmo avaliado, realizaram-se <strong>30 execuções independentes</strong> (<span class="math inline">\(n = 30\)</span>) variando a origem de forma aleatória, calculando-se média, desvio padrão e Intervalo de Confiança (IC) de 95% através da aproximação normal (Z), visto que <span class="math inline">\(n \geq 30\)</span>.</p>
</section>
</section>
<section id="resultados-obtidos" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Resultados Obtidos</h1>
<section id="tratamento-dos-dados" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="tratamento-dos-dados"><span class="header-section-number">5.1</span> Tratamento dos Dados</h2>
<p>Antes do início dos cálculos, os seguintes passos de limpeza e tratamento foram aplicados: 1. Carregamento do arquivo de arestas via <code>cuDF</code> e inicialização do objeto Graph no <code>cuGraph</code>. 2. Verificação de auto-laços: não foram encontrados auto-laços no dataset original (0 arestas removidas). 3. Componentes conexas: confirmou-se que o grafo original é composto por uma única grande componente conexa (LCC) abrangendo todos os 3.997.962 nós. 4. Conversão de estruturas de dados para compatibilidade com o NetworkX (CPU) nos algoritmos específicos.</p>
</section>
<section id="análise-estrutural-do-grafo-completo" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="análise-estrutural-do-grafo-completo"><span class="header-section-number">5.2</span> Análise Estrutural do Grafo Completo</h2>
<p>As métricas estruturais exatas e estimadas por amostragem obtidas neste trabalho estão sumarizadas na <a href="#tbl-estruturais" class="quarto-xref">Table&nbsp;<span>5.1</span></a>.</p>
<div id="tbl-estruturais" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-estruturais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Métricas estruturais computadas para o grafo LiveJournal
</figcaption>
<div aria-describedby="tbl-estruturais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Métrica</th>
<th style="text-align: left;">Valor Computado</th>
<th style="text-align: left;">Método / Detalhe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Número de vértices</td>
<td style="text-align: left;">3.997.962</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Número de arestas</td>
<td style="text-align: left;">34.681.189</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grau mínimo</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grau máximo</td>
<td style="text-align: left;">29.630</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grau médio</td>
<td style="text-align: left;">34,6989</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grau mediano</td>
<td style="text-align: left;">12,0</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Densidade</td>
<td style="text-align: left;"><span class="math inline">\(4,34 \times 10^{-6}\)</span></td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nº componentes conexas</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tamanho da LCC</td>
<td style="text-align: left;">3.997.962</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diâmetro (LCC)</td>
<td style="text-align: left;"><span class="math inline">\(\approx 16\)</span></td>
<td style="text-align: left;">Amostragem (<span class="math inline">\(k=500\)</span> na GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Raio (LCC)</td>
<td style="text-align: left;"><span class="math inline">\(\approx 12\)</span></td>
<td style="text-align: left;">Amostragem (<span class="math inline">\(k=500\)</span> na GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comprimento médio (LCC)</td>
<td style="text-align: left;"><span class="math inline">\(5,5592 \pm 0,6265\)</span></td>
<td style="text-align: left;">Amostragem (<span class="math inline">\(k=500\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IC 95% comprimento médio</td>
<td style="text-align: left;"><span class="math inline">\([5,5043; 5,6141]\)</span></td>
<td style="text-align: left;">Normal (Z, <span class="math inline">\(n=500\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coef. clusterização médio</td>
<td style="text-align: left;">0,061295</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Número de triângulos</td>
<td style="text-align: left;">177.820.130</td>
<td style="text-align: left;">Exato (GPU)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>O diâmetro estimado de 16 obtido pela nossa amostragem está muito próximo ao valor de referência oficial de 17. O comprimento médio dos caminhos (<span class="math inline">\(\approx 5,56\)</span>) confirma que, em média, quaisquer dois usuários estão separados por menos de 6 conexões de amizade.</p>
<div id="fig-dist-excentricidade" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dist-excentricidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/images/fig2_dist_grau_excentricidade.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dist-excentricidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Distribuição de graus em escala log-log (esquerda) e distribuição empírica das excentricidades amostradas (direita).
</figcaption>
</figure>
</div>
<p>A <a href="#fig-dist-excentricidade" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> apresenta as distribuições visuais de graus e caminhos mais curtos: - <strong>Painel esquerdo:</strong> A distribuição de graus plotada em escala log-log revela um decaimento linear marcante, indicando uma distribuição de graus que segue uma lei de potência (propriedade scale-free). A maioria dos usuários possui grau baixo (mediana de 12), enquanto um número pequeno de hubs acumula dezenas de milhares de conexões de amizade (grau máximo de 29.630). - <strong>Painel direito:</strong> A distribuição de excentricidades calculada para a amostra de 500 nós concentra-se no intervalo de 13 a 15, com pouca variação, confirmando que a maioria dos vértices está a distâncias bastante similares do centro de gravidade da rede.</p>
</section>
<section id="desempenho-dos-algoritmos" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="desempenho-dos-algoritmos"><span class="header-section-number">5.3</span> Desempenho dos Algoritmos</h2>
<p>A <a href="#tbl-desempenho" class="quarto-xref">Table&nbsp;<span>5.2</span></a> apresenta os resultados empíricos das medições de tempo de execução no benchmark de algoritmos.</p>
<div id="tbl-desempenho" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-desempenho-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Resultados de tempo de execução e intervalos de confiança (30 repetições)
</figcaption>
<div aria-describedby="tbl-desempenho-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Algoritmo</th>
<th style="text-align: left;">Complexidade</th>
<th style="text-align: left;">Média (ms)</th>
<th style="text-align: left;">IC 95% (ms)</th>
<th style="text-align: left;">Escopo / Dispositivo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BFS</td>
<td style="text-align: left;"><span class="math inline">\(O(V+E)\)</span></td>
<td style="text-align: left;">48,34</td>
<td style="text-align: left;"><span class="math inline">\([45,73; 50,95]\)</span></td>
<td style="text-align: left;">Grafo completo (GPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">DFS</td>
<td style="text-align: left;"><span class="math inline">\(O(V+E)\)</span></td>
<td style="text-align: left;">26.679,76</td>
<td style="text-align: left;"><span class="math inline">\([24.855,80; 28.503,72]\)</span></td>
<td style="text-align: left;">Grafo completo (CPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eulerianidade</td>
<td style="text-align: left;"><span class="math inline">\(O(V+E)\)</span></td>
<td style="text-align: left;">1.533,44</td>
<td style="text-align: left;"><span class="math inline">\([1.526,62; 1.540,26]\)</span></td>
<td style="text-align: left;">Grafo completo (CPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bellman-Ford</td>
<td style="text-align: left;"><span class="math inline">\(O(V \cdot E)\)</span></td>
<td style="text-align: left;">4,40</td>
<td style="text-align: left;"><span class="math inline">\([-0,39; 9,20]\)</span></td>
<td style="text-align: left;">Subgrafo 1.000 nós (CPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Floyd-Warshall</td>
<td style="text-align: left;"><span class="math inline">\(O(V^3)\)</span></td>
<td style="text-align: left;">74.191,24</td>
<td style="text-align: left;"><span class="math inline">\([73.389,16; 74.993,33]\)</span></td>
<td style="text-align: left;">Subgrafo 1.000 nós (CPU)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prim</td>
<td style="text-align: left;"><span class="math inline">\(O(E \log V)\)</span></td>
<td style="text-align: left;">438,98</td>
<td style="text-align: left;"><span class="math inline">\([425,96; 451,99]\)</span></td>
<td style="text-align: left;">Grafo completo (GPU)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kruskal</td>
<td style="text-align: left;"><span class="math inline">\(O(E \log E)\)</span></td>
<td style="text-align: left;">141.403,39</td>
<td style="text-align: left;"><span class="math inline">\([136.142,28; 146.664,49]\)</span></td>
<td style="text-align: left;">Grafo completo (CPU)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-tempo-execucao" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tempo-execucao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/images/fig3_tempo_execucao.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tempo-execucao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Comparação dos tempos médios de execução com intervalos de confiança de 95% em escala logarítmica.
</figcaption>
</figure>
</div>
<p>A <a href="#fig-tempo-execucao" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> ilustra a enorme disparidade de desempenho entre os ambientes GPU e CPU. - <strong>Aceleração na GPU:</strong> Os algoritmos paralelizados em GPU apresentaram tempos de execução extremamente reduzidos. No grafo completo, a BFS rodou em média em 48 ms e o Prim em 439 ms. Em contrapartida, a DFS na CPU exigiu 26,68 segundos para varrer o mesmo grafo, o que representa um speedup de <strong>~553×</strong> a favor da BFS na GPU, mesmo com a mesma complexidade teórica assintótica (<span class="math inline">\(O(V+E)\)</span>). - <strong>Sobrecarga de Algoritmos Inviáveis:</strong> O algoritmo de Kruskal (CPU) rodou no grafo completo com tempo médio de 141,4 segundos devido ao custo de ordenar e unir 34 milhões de arestas em CPU de forma puramente sequencial. Bellman-Ford e Floyd-Warshall foram restritos ao subgrafo de 1.000 nós para evitar travamentos, e o Floyd-Warshall (cúbico) ainda assim demorou em média 74,19 segundos para resolver a amostragem pequena.</p>
</section>
<section id="propriedade-small-world" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="propriedade-small-world"><span class="header-section-number">5.4</span> Propriedade Small-World</h2>
<p>A propriedade small-world foi avaliada de acordo com a formulação clássica de Watts-Strogatz. Comparamos o coeficiente de agrupamento médio (<span class="math inline">\(C\)</span>) e a distância média (<span class="math inline">\(L\)</span>) com os de um grafo aleatório equivalente (modelo Erdős-Rényi com igual número de nós e arestas, onde a probabilidade de conexão é <span class="math inline">\(p \approx 2E / (V(V-1)) \approx 4,34 \times 10^{-6}\)</span>).</p>
<p>As métricas calculadas e os critérios formais para a classificação são detalhados na <a href="#tbl-smallworld" class="quarto-xref">Table&nbsp;<span>5.3</span></a>.</p>
<div id="tbl-smallworld" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-smallworld-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Métricas comparativas para avaliação de rede small-world
</figcaption>
<div aria-describedby="tbl-smallworld-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Critério</th>
<th style="text-align: left;">Valor Observado</th>
<th style="text-align: left;">Condição Esperada</th>
<th style="text-align: left;">Conclusão</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C_{\text{real}} / C_{\text{random}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\approx 7061,64\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\gg 1\)</span></td>
<td style="text-align: left;">Satisfeito</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(L_{\text{real}} / L_{\text{random}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\approx 1,297\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\approx 1\)</span></td>
<td style="text-align: left;">Satisfeito</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Índice <span class="math inline">\(\sigma\)</span> (sigma)</td>
<td style="text-align: left;"><span class="math inline">\(\approx 5444,60\)</span></td>
<td style="text-align: left;"><span class="math inline">\(&gt; 1\)</span></td>
<td style="text-align: left;">Small-world forte</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A razão entre os coeficientes de agrupamento indica que a probabilidade de dois vizinhos de um mesmo usuário serem amigos entre si na rede real é <strong>mais de 7.000 vezes maior</strong> que no modelo aleatório. Somando isso ao fato de que as distâncias médias na rede são apenas 30% maiores que no limite aleatório teórico (<span class="math inline">\(5,56\)</span> contra <span class="math inline">\(4,29\)</span>), confirma-se a presença de uma rede small-world. A topologia combina aglomeração local com atalhos globais, gerando um índice <span class="math inline">\(\sigma\)</span> extremamente elevado.</p>
</section>
<section id="análise-de-lei-de-potência-power-law" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="análise-de-lei-de-potência-power-law"><span class="header-section-number">5.5</span> Análise de Lei de Potência (Power Law)</h2>
<p>A distribuição empírica dos graus foi submetida a um ajuste estatístico por meio de regressão OLS (mínimos quadrados ordinários) em escala log-log, buscando avaliar a hipótese de decaimento em escala livre (<span class="math inline">\(P(k) \sim k^{-\gamma}\)</span>).</p>
<div id="fig-lei-potencia" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lei-potencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/images/fig4_lei_potencia.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lei-potencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Ajuste de regressão OLS em escala log-log da distribuição empírica de graus.
</figcaption>
</figure>
</div>
<p>A <a href="#fig-lei-potencia" class="quarto-xref">Figure&nbsp;<span>5.3</span></a> apresenta o resultado do ajuste linear: - O coeficiente angular da reta ajustada estimou o expoente de decaimento em <span class="math inline">\(\gamma \approx 2,44\)</span>. - O coeficiente de determinação obtido foi de <span class="math inline">\(R^2 = 0,924\)</span>, indicando que a distribuição empírica dos graus é fortemente modelada por uma lei de potência em quase toda a sua extensão (do grau mínimo 2 ao grau máximo de hubs 29.630). - Esse valor de expoente (<span class="math inline">\(2 &lt; \gamma &lt; 3\)</span>) é o comportamento padrão observado na literatura científica para grandes redes de amizade online, implicando em uma rede altamente heterogênea onde a média dos graus (<span class="math inline">\(\approx 34,7\)</span>) perde o caráter representativo diante de uma mediana baixa (12) e cauda longa com hubs gigantescos.</p>
</section>
<section id="robustez-da-rede" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="robustez-da-rede"><span class="header-section-number">5.6</span> Robustez da Rede</h2>
<p>A robustez estrutural do LiveJournal foi testada sob dois cenários distintos de degradação: 1. <strong>Falha Aleatória:</strong> Remoção de 5% dos nós escolhidos de forma uniforme ao acaso (com <span class="math inline">\(T=30\)</span> repetições independentes). 2. <strong>Ataque Direcionado:</strong> Remoção dos 5% de nós mais centrais, ordenados de forma decrescente pela centralidade de grau (<em>degree centrality</em>).</p>
<p>Os resultados médios obtidos após a remoção sistemática dos nós são exibidos na <a href="#tbl-robustez" class="quarto-xref">Table&nbsp;<span>5.4</span></a>.</p>
<div id="tbl-robustez" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-robustez-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.4: Resumo de métricas obtidas na análise de robustez e degradação
</figcaption>
<div aria-describedby="tbl-robustez-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Métrica</th>
<th style="text-align: left;">Rede Original</th>
<th style="text-align: left;">Remoção Aleatória (5%, T=30)</th>
<th style="text-align: left;">Ataque a Hubs (5%, degree)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fração do tamanho da LCC</td>
<td style="text-align: left;">1,0000</td>
<td style="text-align: left;"><span class="math inline">\(0,9385 \pm 0,0001\)</span></td>
<td style="text-align: left;">0,8912 (<span class="math inline">\(\Delta = -0,1088\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nº de componentes conexas</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;"><span class="math inline">\(2.705,6 \pm 62,5\)</span></td>
<td style="text-align: left;"><span class="math inline">\(11.174\)</span> (<span class="math inline">\(\Delta = +11.173\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Distância média estimada</td>
<td style="text-align: left;">5,6753</td>
<td style="text-align: left;"><span class="math inline">\(5,6057 \pm 0,0704\)</span></td>
<td style="text-align: left;">7,3709 (<span class="math inline">\(\Delta = +1,6956\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fração de nós isolados</td>
<td style="text-align: left;">0,000000</td>
<td style="text-align: left;"><span class="math inline">\(0,000000 \pm 0,000000\)</span></td>
<td style="text-align: left;">0,000000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-robustez" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-robustez-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/images/fig5_robustez.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-robustez-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Comportamento comparativo das métricas de robustez sob falhas aleatórias e ataques direcionados.
</figcaption>
</figure>
</div>
<p>A análise comparativa por meio da <a href="#fig-robustez" class="quarto-xref">Figure&nbsp;<span>5.4</span></a> demonstra o comportamento dual clássico de redes scale-free <span class="citation" data-cites="barabasi2000">(<a href="#ref-barabasi2000" role="doc-biblioref">Albert, Jeong, and Barabási 2000</a>)</span>: - <strong>Resiliência a Falhas Aleatórias:</strong> A rede é extremamente resiliente à quebra fortuita de nós. A remoção aleatória de 5% da população (quase 200 mil usuários) preserva 93,85% do tamanho da maior componente conexa e mantém a distância média global estável em <span class="math inline">\(\approx 5,60\)</span> saltos. O desvio padrão insignificante confirma a homogeneidade desse resultado independente dos nós sorteados. - <strong>Vulnerabilidade a Ataques Direcionados:</strong> A rede é severamente degradada sob ataque direcionado aos hubs. Ao remover os 5% de nós com maior grau, a LCC é reduzida para 89,12% (uma queda muito mais abrupta) e a rede se fragmenta massivamente, originando mais de 11.000 componentes isoladas (cerca de 4× a fragmentação do cenário aleatório). Além disso, a distância média entre nós na componente restante aumenta cerca de 30% (de 5,68 para 7,37). A destruição dos hubs remove os principais “atalhos” e pontes estruturais da rede, forçando as comunicações remanescentes a contornar por rotas periféricas.</p>
</section>
</section>
<section id="discussão-crítica" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussão Crítica</h1>
<section id="decisões-de-projeto-e-viabilidade" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="decisões-de-projeto-e-viabilidade"><span class="header-section-number">6.1</span> Decisões de Projeto e Viabilidade</h2>
<p>A decisão metodológica mais crucial do projeto foi a substituição do cálculo exato de caminhos mínimos globais (cujo diâmetro exato requer rodar BFS para todos os 4 milhões de nós) por uma amostragem representativa de <span class="math inline">\(k=500\)</span> nós. O cálculo exato exigiria cerca de <span class="math inline">\(1,55 \times 10^{14}\)</span> operações e aproximadamente 43 horas de computação contínua de GPU, inviabilizando a execução no prazo do trabalho. A validação cruzada do diâmetro estimado de 16 frente ao real de 17 reportado pelo SNAP corroborou a eficiência estatística da amostragem com margem de erro pequena.</p>
<p>A aceleração em GPU com cuGraph revelou-se indispensável. Operações elementares que rodam na ordem de milissegundos em GPU levam dezenas de segundos na CPU para o mesmo grafo (como a BFS rodando a 48 ms na GPU contra a DFS a 26,68 s na CPU). Contudo, evidenciou-se que nem todos os algoritmos ganham aceleração trivial por meio do paralelismo. Algoritmos intrinsicamente sequenciais ou que exigem sincronismo estrito de pilhas (como a DFS) não são bem representados na arquitetura Massivamente Paralela de CUDA, justificando a decisão de implementá-los na CPU mesmo diante de tempos mais elevados.</p>
</section>
<section id="limitações-metodológicas-e-estruturais" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="limitações-metodológicas-e-estruturais"><span class="header-section-number">6.2</span> Limitações Metodológicas e Estruturais</h2>
<p>A análise revelou duas categorias de limitações importantes: 1. <strong>Limitações Estruturais:</strong> Os algoritmos de Dijkstra e Tarjan foram excluídos da medição por premissas incompatíveis. O Dijkstra pressupõe arestas com pesos (o grafo original é não ponderado) e o Tarjan é focado na identificação de componentes fortemente conexas em grafos direcionados (a rede do LiveJournal é modelada de forma não direcionada). 2. <strong>Limitações Computacionais:</strong> A execução de algoritmos quadráticos e cúbicos (Bellman-Ford e Floyd-Warshall) no grafo completo é computacionalmente proibitiva até em ambientes com aceleração por hardware. A amostragem de subgrafo com 1.000 nós permitiu validar os algoritmos, mas impede a extrapolação direta dos tempos médios observados para a escala global do LiveJournal.</p>
<p>A escolha da centralidade de grau (<em>degree centrality</em>) em detrimento da centralidade de intermediação (<em>betweenness centrality</em>) na análise de robustez baseou-se na complexidade de cálculo. O cálculo exato da centralidade de intermediação requer resolver caminhos mínimos de todos para todos (complexidade <span class="math inline">\(O(V \cdot E)\)</span>), o que é inviável na rede completa. A centralidade de grau, computável em complexidade constante por vértice (<span class="math inline">\(O(1)\)</span>) após obter o vetor de adjacências, proveu uma aproximação de baixo custo e alta eficiência para o mapeamento dos hubs da rede.</p>
</section>
</section>
<section id="conclusão" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusão</h1>
<p>Este trabalho apresentou uma investigação aprofundada da rede de amizades LiveJournal, composta por 3.997.962 nós e 34.681.189 arestas, aplicando computação de alto desempenho em GPU.</p>
<p>A contagem exata de triângulos (<span class="math inline">\(177.820.130\)</span>) e a BFS em milissegundos validaram a adequação da biblioteca cuGraph para o processamento de redes complexas em escala multimilionária.</p>
<p>Os principais achados científicos do estudo revelaram que: 1. A rede é esparsa, completamente conexa e exibe uma estrutura comunitária local forte, com coeficiente de clusterização exato de <span class="math inline">\(0,0613\)</span>, cerca de 7.000× maior que o de uma rede puramente aleatória. 2. A distância média de <span class="math inline">\(5,56\)</span> saltos confirma que a rede possui a propriedade small-world, aproximando usuários distantes em poucos graus de separação. 3. A distribuição de graus é bem modelada por uma lei de potência com expoente <span class="math inline">\(\gamma \approx 2,44\)</span> (<span class="math inline">\(R^2 = 0,924\)</span>), indicando uma rede sem escala de tamanho (scale-free) altamente heterogênea. 4. A aceleração por GPU proporcionou speedups de até <strong>553×</strong> no grafo completo (como na comparação BFS GPU vs.&nbsp;DFS CPU), demonstrando o impacto prático do hardware de paralelização. 5. O teste de robustez corroborou a clássica tolerância a falhas aleatórias e a extrema sensibilidade a ataques direcionados aos hubs na topologia scale-free.</p>
<p>Essas propriedades possuem implicações práticas diretas. Em uma rede small-world e scale-free, a propagação de informação ou vírus ocorre de forma acelerada devido à presença de atalhos e hubs. Intervenções focadas em moderar ou imunizar os 5% mais influentes da rede (cerca de 200 mil hubs) possuem o potencial de interromper a difusão global ou disseminar campanhas de utilidade pública com eficiência desproporcional.</p>
<p>Como trabalhos futuros, sugere-se a aplicação de algoritmos exatos acelerados em GPU para cálculo de diâmetro (como double sweep ou iFUB) e a realização de análises avançadas de comunidade sobre o conjunto de dados <em>com-lj.all.cmty.txt</em> e <em>com-lj.top5000.cmty.txt</em> fornecidos pelo repositório SNAP.</p>
<section id="agradecimentos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="agradecimentos">Agradecimentos</h2>
<p>Agradecemos ao laboratório BAMBU Lab (UFBA) pela disponibilização da infraestrutura computacional de alto desempenho com GPUs NVIDIA RTX A4000. Estendemos os agradecimentos ao Stanford Network Analysis Project (SNAP) por organizar e disponibilizar o dataset, e ao professor Dr.&nbsp;Bruno P. S. pelas discussões e incentivo à experimentação prática das métricas ao longo da disciplina MATA53 - Teoria dos Grafos.</p>
</section>
</section>
<section id="apêndice" class="level1 unnumbered">
<h1 class="unnumbered">Apêndice</h1>
<section id="repositório-e-instruções-de-execução" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="repositório-e-instruções-de-execução"><span class="header-section-number">7.1</span> Repositório e Instruções de Execução</h2>
<p>O código-fonte e scripts de automação deste projeto podem ser consultados no GitHub: - <strong>URL:</strong> <a href="https://github.com/Carolbalbs/tp-final" class="uri">https://github.com/Carolbalbs/tp-final</a></p>
<p>O repositório do projeto está estruturado da seguinte forma: - <code>scripts/</code> — Contém os notebooks Jupyter e scripts Python (<code>parte1.py</code>, <code>parte2.py</code>, <code>parte3_ab.py</code>, <code>parte3_c.py</code>, <code>driver.py</code>) que realizam o processamento de dados e plotagem na GPU. - <code>scripts/logs/</code> — Armazena as saídas de execução no servidor para fins de repositibilidade. - <code>data/</code> — Contém arquivos de checkpoints e saídas dos experimentos. - <code>data/images/</code> — Contém as figuras e visualizações geradas para o relatório final. - <code>README.md</code> — Manual de instruções contendo os requisitos e comandos de execução dos scripts em container Podman.</p>
<pre class="bash"><code># Exemplo de comando para executar as análises no servidor via container
podman exec -d projeto_odonto bash -c \
  "/opt/grafos-env/bin/python /shared/driver.py &gt; /shared/driver.log 2&gt;&amp;1"</code></pre>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-barabasi2000" class="csl-entry" role="listitem">
Albert, Réka, Hawoong Jeong, and Albert-László Barabási. 2000. <span>“Error and Attack Tolerance of Complex Networks.”</span> <em>Nature</em> 406 (6794): 378–82.
</div>
<div id="ref-yang2012" class="csl-entry" role="listitem">
Yang, Jaewon, and Jure Leskovec. 2012. <span>“Defining and Evaluating Network Communities Based on Ground-Truth.”</span> In <em>Proceedings of the 2012 IEEE 12th International Conference on Data Mining</em>, 745–54. IEEE.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Introdução">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introdução</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./parte1_all.html" class="pagination-link" aria-label="Análise Estrutura - Comunidades">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análise Estrutura - Comunidades</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/carolbalbs/tp-final/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>